CREATE TABLE "SYSTEM"."ARTICLE"
   (	"ID" NUMBER(19,0) NOT NULL ENABLE,
	"AUTHOR_ID" NUMBER(19,0) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6),
	"UPDATED_AT" TIMESTAMP (6),
	 CONSTRAINT "ARTICLE_ID_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "ARTICLE_AUTHOR_ID_FK" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "SYSTEM"."USER" ("ID") ENABLE
   );

CREATE TABLE "SYSTEM"."ARTICLE_DETAILS"
   (	"ARTICLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"LANG_ID" VARCHAR2(255) NOT NULL ENABLE,
	"TITLE" VARCHAR2(255) NOT NULL ENABLE,
	"CONTEXT" CLOB NOT NULL ENABLE,
	 CONSTRAINT "ARTICLE_DETAILS_LANG" UNIQUE ("ARTICLE_ID", "LANG_ID") ENABLE,
	 CONSTRAINT "ARTICLE_DETAILS_ARTICLE_ID_FK" FOREIGN KEY ("ARTICLE_ID")
	  REFERENCES "SYSTEM"."ARTICLE" ("ID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "SYSTEM"."ARTICLE_DETAILS_HISTORY"
   (	"ID" NUMBER(19,0) NOT NULL ENABLE,
	"ARTICLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"AUTHOR_ID" NUMBER(19,0) NOT NULL ENABLE,
	"BASE_ID" NUMBER(19,0),
	"STATE" VARCHAR2(255) NOT NULL ENABLE,
	"REVIEWER_ID" NUMBER(19,0),
	"LANG_ID" VARCHAR2(255) NOT NULL ENABLE,
	"TITLE" VARCHAR2(255) NOT NULL ENABLE,
	"CONTEXT" CLOB NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6),
	"UPDATED_AT" TIMESTAMP (6),
	 CONSTRAINT "ARTICLE_DETAILS_HISTORY_ID_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "ARTIC_DETAI_HISTO_AUTH_ID_FK" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "SYSTEM"."USER" ("ID") ENABLE,
	 CONSTRAINT "ARTIC_DETAI_HISTO_ARTIC_ID_FK" FOREIGN KEY ("ARTICLE_ID")
	  REFERENCES "SYSTEM"."ARTICLE" ("ID") ENABLE,
	 CONSTRAINT "ARTICL_DETAIL_HISTOR_BAS_ID_FK" FOREIGN KEY ("BASE_ID")
	  REFERENCES "SYSTEM"."ARTICLE_DETAILS_HISTORY" ("ID") ENABLE,
	 CONSTRAINT "ARTIC_DETAI_HISTO_REVIEW_ID_FK" FOREIGN KEY ("REVIEWER_ID")
	  REFERENCES "SYSTEM"."USER" ("ID") ENABLE
   );

CREATE TABLE "SYSTEM"."ARTICLE_PARTICIPANT"
   (	"ARTICLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"USER_ID" NUMBER(19,0) NOT NULL ENABLE,
	 CONSTRAINT "ARTICLE_PARTICIPANT_UDX" UNIQUE ("ARTICLE_ID", "USER_ID") ENABLE,
	 CONSTRAINT "ARTICL_PARTICIPAN_ARTICL_ID_FK" FOREIGN KEY ("ARTICLE_ID")
	  REFERENCES "SYSTEM"."ARTICLE" ("ID") ENABLE,
	 CONSTRAINT "ARTICLE_PARTICIPANT_USER_ID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USER" ("ID") ENABLE
   );

CREATE TABLE "SYSTEM"."ARTICLE_TAG"
   (	"ARTICLE_ID" NUMBER(19,0) NOT NULL ENABLE,
	"LANG_ID" VARCHAR2(255) NOT NULL ENABLE,
	"TAG" VARCHAR2(255) NOT NULL ENABLE,
	 CONSTRAINT "ARTICLE_DETAILS_TAG" UNIQUE ("ARTICLE_ID", "LANG_ID", "TAG") ENABLE
   );

CREATE TABLE "SYSTEM"."ARTICLE_TAG_HISTORY"
   (	"ARTICLE_DETAILS_HISTORY_ID" NUMBER(19,0) NOT NULL ENABLE,
	"TAG" VARCHAR2(255) NOT NULL ENABLE,
	 CONSTRAINT "ARTICLE_DETAILS_HISTORY_TAG" UNIQUE ("ARTICLE_DETAILS_HISTORY_ID", "TAG") ENABLE,
	 CONSTRAINT "ART_TA_HIS_ART_DET_HIS_ID_FK" FOREIGN KEY ("ARTICLE_DETAILS_HISTORY_ID")
	  REFERENCES "SYSTEM"."ARTICLE_DETAILS_HISTORY" ("ID") ENABLE
   );

CREATE TABLE "SYSTEM"."MIGRATIONS"
   (	"ID" NUMBER(10,0) NOT NULL ENABLE,
	"MIGRATION" VARCHAR2(255) NOT NULL ENABLE,
	"BATCH" NUMBER(10,0) NOT NULL ENABLE,
	 CONSTRAINT "MIGRATIONS_ID_PK" PRIMARY KEY ("ID") ENABLE
   );

CREATE TABLE "SYSTEM"."PASSWORD_RESET"
   (	"EMAIL" VARCHAR2(255) NOT NULL ENABLE,
	"TOKEN" VARCHAR2(255) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6)
   );

CREATE TABLE "SYSTEM"."USER"
   (	"ID" NUMBER(19,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(255) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(255) NOT NULL ENABLE,
	"EMAIL_VERIFIED_AT" TIMESTAMP (6),
	"PASSWORD" VARCHAR2(255) NOT NULL ENABLE,
	"REMEMBER_TOKEN" VARCHAR2(100),
	"CREATED_AT" TIMESTAMP (6),
	"UPDATED_AT" TIMESTAMP (6),
	"ROLE" VARCHAR2(255) DEFAULT 'user' NOT NULL ENABLE,
	"ACADEMIC_DEGREE" VARCHAR2(255),
	"INSTITUTION" VARCHAR2(255),
	"SPECIALIZATION" VARCHAR2(255),
	"AVATAR" VARCHAR2(255),
	 CONSTRAINT "USER_ID_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "USER_EMAIL_UK" UNIQUE ("EMAIL") ENABLE
   );

CREATE TABLE "SYSTEM"."USER_LANGUAGE"
   (	"USER_ID" NUMBER(19,0) NOT NULL ENABLE,
	"LANG_ID" VARCHAR2(2) NOT NULL ENABLE,
	"TYPE" VARCHAR2(255) NOT NULL ENABLE,
	 CONSTRAINT "USER_LANGUAGE" UNIQUE ("LANG_ID", "TYPE") ENABLE,
	 CONSTRAINT "USER_LANGUAGE_USER_ID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."USER" ("ID") ENABLE
   );
